# Internship Task

In [94]:
# imprted required libraries to understand data
import pandas as pd , numpy as np

In [95]:
# importing sample stock market dataset
df = pd.read_excel('SampleStockMarketData.xlsx')

## Understanding Dataset

In [96]:
# printing first 5 rows in order to understand Data
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Ticker,Date,Time,Open,High,Low,Close,Volume,Open Interest
1,BANKNIFTY01APR2130600CE.NFO,2021-03-01 00:00:00,14:39:59,5057.2,5065,5057.2,5065,50,48000
2,BANKNIFTY01APR2130600CE.NFO,2021-03-01 00:00:00,15:09:59,5065,5065,4604.95,4604.95,25,48000
3,BANKNIFTY01APR2130700CE.NFO,2021-03-01 00:00:00,15:00:59,4855,4860,4855,4860,100,48000
4,BANKNIFTY01APR2130700PE.NFO,2021-03-01 00:00:00,14:14:59,140.6,140.6,137,137,4550,47750

In [97]:
df.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
82861,BANKNIFTY-III.NFO,2021-03-01 00:00:00,15:20:59,35555,35555,35500,35500,100,292500
82862,BANKNIFTY-III.NFO,2021-03-01 00:00:00,15:23:59,35500,35514.05,35500,35514.05,25,292525
82863,BANKNIFTY-III.NFO,2021-03-01 00:00:00,15:24:59,35514.05,35514.05,35514.05,35514.05,50,292525
82864,BANKNIFTY-III.NFO,2021-03-01 00:00:00,15:25:59,35514.05,35546.55,35514.05,35546.55,25,292475
82865,BANKNIFTY-III.NFO,2021-03-01 00:00:00,15:29:59,35546.55,35546.55,35543,35545,75,292450

In [98]:
df.shape

(82866, 9)

In [99]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8'],
      dtype='object')

Column names are not displayed as it should be so data need to be cleaned.

In [100]:
df.nunique()

Unnamed: 0      542
Unnamed: 1        2
Unnamed: 2      377
Unnamed: 3    25665
Unnamed: 4    24514
Unnamed: 5    24258
Unnamed: 6    25892
Unnamed: 7     2670
Unnamed: 8    10026
dtype: int64

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82866 entries, 0 to 82865
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  82866 non-null  object
 1   Unnamed: 1  82866 non-null  object
 2   Unnamed: 2  82866 non-null  object
 3   Unnamed: 3  82866 non-null  object
 4   Unnamed: 4  82866 non-null  object
 5   Unnamed: 5  82866 non-null  object
 6   Unnamed: 6  82866 non-null  object
 7   Unnamed: 7  82866 non-null  object
 8   Unnamed: 8  82866 non-null  object
dtypes: object(9)
memory usage: 5.7+ MB

# Data Cleaning

In [102]:
# removed unwanted row
df = pd.read_excel('SampleStockMarketData.xlsx', skiprows = 1 )
df.head()

,Ticker,Date,Time,Open,High,Low,Close,Volume,Open Interest
0,BANKNIFTY01APR2130600CE.NFO,2021-03-01,14:39:59,5057.2,5065.0,5057.20,5065.00,50,48000
1,BANKNIFTY01APR2130600CE.NFO,2021-03-01,15:09:59,5065.0,5065.0,4604.95,4604.95,25,48000
2,BANKNIFTY01APR2130700CE.NFO,2021-03-01,15:00:59,4855.0,4860.0,4855.00,4860.00,100,48000
3,BANKNIFTY01APR2130700PE.NFO,2021-03-01,14:14:59,140.6,140.6,137.00,137.00,4550,47750
4,BANKNIFTY01APR2130700PE.NFO,2021-03-01,14:15:59,137.0,143.6,137.00,140.00,4550,47750

In [103]:
df.columns

Index(['Ticker', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume',
       'Open Interest'],
      dtype='object')

### checking for null values

In [104]:
df.isnull().sum()

Ticker           0
Date             0
Time             0
Open             0
High             0
Low              0
Close            0
Volume           0
Open Interest    0
dtype: int64

This shows that there are not any null values in the Dataset. So, no need to remove or replace values in the Dataset.

### Checking for duplicate values

In [105]:
df.duplicated().sum()

0

### 1) Classify the options data into various expiries dates. Various expiry dates are mentioned as 04Mar21, 01Apr21, 11Mar21 and so on. Every Thursday there is an expiry.

In [106]:
df['Date'] = df['Date'].astype(str) +" "+ df["Time"].astype(str)

In [107]:
# Converting Date column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

In [108]:
# Creating a list of expiry dates
expiry_dates = []
for i in range(4):
    thursday = df['Date'].min() + pd.DateOffset(days=(3-df['Date'].min().weekday()+7*i))
    expiry_dates.append(thursday.strftime('%d%b%y').upper())

In [109]:
# Creating a dictionary to store options data by expiry date
expiry_data = {}
for date in expiry_dates:
    expiry_data[date] = {}

In [110]:
# Looping through each row in the dataframe and add options data to the corresponding expiry date
for index, row in df.iterrows():
    date = row['Date']
    expiry = (date + pd.DateOffset(days=(3-date.weekday()))).strftime('%d%b%y').upper()
    ticker = row['Ticker']
    open_interest = row['Open Interest']
    if expiry in expiry_dates:
        if ticker not in expiry_data[expiry]:
            expiry_data[expiry][ticker] = {'Open Interest': 0}
        expiry_data[expiry][ticker]['Open Interest'] += open_interest

In [111]:
# Printing the expiry data
for expiry, data in expiry_data.items():
    print(expiry)
    print("-" * 20)
    for ticker, ticker_data in data.items():
        open_interest = ticker_data['Open Interest']
        print(f"{ticker}: {open_interest}")
    print("=" * 20)

04MAR21
--------------------
BANKNIFTY01APR2130600CE.NFO: 96000
BANKNIFTY01APR2130700CE.NFO: 48000
BANKNIFTY01APR2130700PE.NFO: 143250
BANKNIFTY01APR2131400CE.NFO: 180750
BANKNIFTY01APR2131500PE.NFO: 120575
BANKNIFTY04MAR2127300PE.NFO: 21984975
BANKNIFTY04MAR2127500PE.NFO: 17928050
BANKNIFTY04MAR2128000PE.NFO: 1421375
BANKNIFTY04MAR2129000PE.NFO: 2314225
BANKNIFTY04MAR2129500PE.NFO: 24275
BANKNIFTY04MAR2129900PE.NFO: 522250
BANKNIFTY04MAR2130000CE.NFO: 9025
BANKNIFTY04MAR2130000PE.NFO: 112113900
BANKNIFTY04MAR2130100PE.NFO: 203700
BANKNIFTY04MAR2130200PE.NFO: 288750
BANKNIFTY04MAR2130400PE.NFO: 126200
BANKNIFTY04MAR2130500PE.NFO: 37164325
BANKNIFTY04MAR2130600PE.NFO: 39725
BANKNIFTY04MAR2130800PE.NFO: 127725
BANKNIFTY04MAR2130900PE.NFO: 2201175
BANKNIFTY04MAR2131000CE.NFO: 11150
BANKNIFTY04MAR2131000PE.NFO: 96864500
BANKNIFTY04MAR2131100PE.NFO: 606900
BANKNIFTY04MAR2131200PE.NFO: 1871725
BANKNIFTY04MAR2131300PE.NFO: 2596000
BANKNIFTY04MAR2131400PE.NFO: 3074000
BANKNIFTY04MAR2131500CE.NFO: 10125
BANKNIFTY04MAR2131500PE.NFO: 125955425
BANKNIFTY04MAR2131600PE.NFO: 5265475
BANKNIFTY04MAR2131700PE.NFO: 6042025
BANKNIFTY04MAR2131800PE.NFO: 9871050
BANKNIFTY04MAR2131900CE.NFO: 25
BANKNIFTY04MAR2131900PE.NFO: 7503300
BANKNIFTY04MAR2132000CE.NFO: 44075
BANKNIFTY04MAR2132000PE.NFO: 146033525
BANKNIFTY04MAR2132100CE.NFO: 25
BANKNIFTY04MAR2132100PE.NFO: 11362225
BANKNIFTY04MAR2132200CE.NFO: 25
BANKNIFTY04MAR2132200PE.NFO: 10687925
BANKNIFTY04MAR2132300PE.NFO: 9355600
BANKNIFTY04MAR2132400CE.NFO: 1625
BANKNIFTY04MAR2132400PE.NFO: 10948625
BANKNIFTY04MAR2132500CE.NFO: 29125
BANKNIFTY04MAR2132500PE.NFO: 127598850
BANKNIFTY04MAR2132600CE.NFO: 1775
BANKNIFTY04MAR2132600PE.NFO: 13644600
BANKNIFTY04MAR2132700CE.NFO: 25
BANKNIFTY04MAR2132700PE.NFO: 13753625
BANKNIFTY04MAR2132800CE.NFO: 8225
BANKNIFTY04MAR2132800PE.NFO: 17866725
BANKNIFTY04MAR2132900CE.NFO: 650
BANKNIFTY04MAR2132900PE.NFO: 12346475
BANKNIFTY04MAR2133000CE.NFO: 625925
BANKNIFTY04MAR2133000PE.NFO: 231718725
BANKNIFTY04MAR2133100PE.NFO: 12849375
BANKNIFTY04MAR2133200CE.NFO: 375
BANKNIFTY04MAR2133200PE.NFO: 21085875
BANKNIFTY04MAR2133300CE.NFO: 50
BANKNIFTY04MAR2133300PE.NFO: 23363000
BANKNIFTY04MAR2133400PE.NFO: 15392925
BANKNIFTY04MAR2133500CE.NFO: 512500
BANKNIFTY04MAR2133500PE.NFO: 183260500
BANKNIFTY04MAR2133600CE.NFO: 46550
BANKNIFTY04MAR2133600PE.NFO: 39954850
BANKNIFTY04MAR2133700CE.NFO: 1375
BANKNIFTY04MAR2133700PE.NFO: 26100100
BANKNIFTY04MAR2133800CE.NFO: 60075
BANKNIFTY04MAR2133800PE.NFO: 29197925
BANKNIFTY04MAR2133900CE.NFO: 13800
BANKNIFTY04MAR2133900PE.NFO: 25088450
BANKNIFTY04MAR2134000CE.NFO: 18579300
BANKNIFTY04MAR2134000PE.NFO: 265976575
BANKNIFTY04MAR2134100CE.NFO: 163350
BANKNIFTY04MAR2134100PE.NFO: 31542850
BANKNIFTY04MAR2134200CE.NFO: 385350
BANKNIFTY04MAR2134200PE.NFO: 46399100
BANKNIFTY04MAR2134300CE.NFO: 191925
BANKNIFTY04MAR2134300PE.NFO: 41447175
BANKNIFTY04MAR2134400CE.NFO: 311650
BANKNIFTY04MAR2134400PE.NFO: 43165825
BANKNIFTY04MAR2134500CE.NFO: 23905050
BANKNIFTY04MAR2134500PE.NFO: 233319475
BANKNIFTY04MAR2134600CE.NFO: 2267650
BANKNIFTY04MAR2134600PE.NFO: 43759575
BANKNIFTY04MAR2134700CE.NFO: 8596950
BANKNIFTY04MAR2134700PE.NFO: 44460525
BANKNIFTY04MAR2134800CE.NFO: 14743250
BANKNIFTY04MAR2134800PE.NFO: 69690300
BANKNIFTY04MAR2134900CE.NFO: 16688900
BANKNIFTY04MAR2134900PE.NFO: 42590950
BANKNIFTY04MAR2135000CE.NFO: 183109025
BANKNIFTY04MAR2135000PE.NFO: 259380075
BANKNIFTY04MAR2135100CE.NFO: 28303325
BANKNIFTY04MAR2135100PE.NFO: 45386975
BANKNIFTY04MAR2135200CE.NFO: 52561925
BANKNIFTY04MAR2135200PE.NFO: 61998050
BANKNIFTY04MAR2135300CE.NFO: 79403575
BANKNIFTY04MAR2135300PE.NFO: 67344550
BANKNIFTY04MAR2135400CE.NFO: 70449025
BANKNIFTY04MAR2135400PE.NFO: 36126525
BANKNIFTY04MAR2135500CE.NFO: 257982050
BANKNIFTY04MAR2135500PE.NFO: 115651150
BANKNIFTY04MAR2135600CE.NFO: 79876975
BANKNIFTY04MAR2135600PE.NFO: 19108575
BANKNIFTY04MAR2135700CE.NFO: 75129175
BANKNIFTY04MAR2135700PE.NFO: 10594300
BANKNIFTY04MAR2135800CE.NFO: 93169600
BANKNIFTY04MAR2135800PE.NFO: 7858775
BANKNIFTY04MAR2135900CE.NFO: 62834775
BANKNIFTY04MAR2135900PE.NFO: 3751725
BANKNIFTY04MAR2136000CE.NFO: 396086825
BANKNIFTY04MAR2136000PE.NFO: 55950275
BANKNIFTY04MAR2136100CE.NFO: 52952700
BANKNIFTY04MAR2136100PE.NFO: 1576300
BANKNIFTY04MAR2136200CE.NFO: 71866875
BANKNIFTY04MAR2136200PE.NFO: 1671925
BANKNIFTY04MAR2136300CE.NFO: 64748550
BANKNIFTY04MAR2136300PE.NFO: 2840300
BANKNIFTY04MAR2136400CE.NFO: 58136825
BANKNIFTY04MAR2136400PE.NFO: 894050
BANKNIFTY04MAR2136500CE.NFO: 290260150
BANKNIFTY04MAR2136500PE.NFO: 26494150
BANKNIFTY04MAR2136600CE.NFO: 43752925
BANKNIFTY04MAR2136600PE.NFO: 2120150
BANKNIFTY04MAR2136700CE.NFO: 46964400
BANKNIFTY04MAR2136700PE.NFO: 2953200
BANKNIFTY04MAR2136800CE.NFO: 62000925
BANKNIFTY04MAR2136800PE.NFO: 1649200
BANKNIFTY04MAR2136900CE.NFO: 40915550
BANKNIFTY04MAR2136900PE.NFO: 258025
BANKNIFTY04MAR2137000CE.NFO: 364897375
BANKNIFTY04MAR2137000PE.NFO: 15354325
BANKNIFTY04MAR2137100CE.NFO: 44441025
BANKNIFTY04MAR2137100PE.NFO: 241350
BANKNIFTY04MAR2137200CE.NFO: 52483475
BANKNIFTY04MAR2137200PE.NFO: 56675
BANKNIFTY04MAR2137300CE.NFO: 37254950
BANKNIFTY04MAR2137300PE.NFO: 83700
BANKNIFTY04MAR2137400CE.NFO: 35243775
BANKNIFTY04MAR2137400PE.NFO: 31100
BANKNIFTY04MAR2137500CE.NFO: 235266750
BANKNIFTY04MAR2137500PE.NFO: 1597050
BANKNIFTY04MAR2137600CE.NFO: 33352400
BANKNIFTY04MAR2137700CE.NFO: 35960950
BANKNIFTY04MAR2137700PE.NFO: 6625
BANKNIFTY04MAR2137800CE.NFO: 35798575
BANKNIFTY04MAR2137800PE.NFO: 725
BANKNIFTY04MAR2137900CE.NFO: 25901475
BANKNIFTY04MAR2137900PE.NFO: 675
BANKNIFTY04MAR2138000CE.NFO: 301943900
BANKNIFTY04MAR2138000PE.NFO: 1098725
BANKNIFTY04MAR2138100CE.NFO: 18276750
BANKNIFTY04MAR2138100PE.NFO: 400
BANKNIFTY04MAR2138200CE.NFO: 31957300
BANKNIFTY04MAR2138200PE.NFO: 175
BANKNIFTY04MAR2138300CE.NFO: 18999025
BANKNIFTY04MAR2138300PE.NFO: 25
BANKNIFTY04MAR2138400CE.NFO: 19933275
BANKNIFTY04MAR2138400PE.NFO: 150
BANKNIFTY04MAR2138500CE.NFO: 267744275
BANKNIFTY04MAR2138500PE.NFO: 74475
BANKNIFTY04MAR2138600CE.NFO: 17908400
BANKNIFTY04MAR2138700CE.NFO: 20090850
BANKNIFTY04MAR2138700PE.NFO: 25
BANKNIFTY04MAR2138800CE.NFO: 21218925
BANKNIFTY04MAR2138800PE.NFO: 25
BANKNIFTY04MAR2138900CE.NFO: 73300800
BANKNIFTY04MAR2138900PE.NFO: 25
BANKNIFTY04MAR2139000CE.NFO: 259381325
BANKNIFTY04MAR2139000PE.NFO: 550
BANKNIFTY04MAR2139100CE.NFO: 8533550
BANKNIFTY04MAR2139200CE.NFO: 5489000
BANKNIFTY04MAR2139200PE.NFO: 25
BANKNIFTY04MAR2139300CE.NFO: 6706575
BANKNIFTY04MAR2139400CE.NFO: 3655000
BANKNIFTY04MAR2139500CE.NFO: 141093975
BANKNIFTY04MAR2139500PE.NFO: 200
BANKNIFTY04MAR2139600CE.NFO: 3035625
BANKNIFTY04MAR2139700CE.NFO: 931525
BANKNIFTY04MAR2139800CE.NFO: 5681975
BANKNIFTY04MAR2139900CE.NFO: 2848975
BANKNIFTY04MAR2140000CE.NFO: 257966475
BANKNIFTY04MAR2140000PE.NFO: 375
BANKNIFTY04MAR2140100CE.NFO: 2892125
BANKNIFTY04MAR2140200CE.NFO: 5176725
BANKNIFTY04MAR2140200PE.NFO: 25
BANKNIFTY04MAR2140300CE.NFO: 173923325
BANKNIFTY04MAR2140300PE.NFO: 25
BANKNIFTY10MAR2129500PE.NFO: 9825
BANKNIFTY10MAR2130000PE.NFO: 1046500
BANKNIFTY10MAR2130500PE.NFO: 8450
BANKNIFTY10MAR2131000PE.NFO: 648600
BANKNIFTY10MAR2131500PE.NFO: 76100
BANKNIFTY10MAR2132000PE.NFO: 4182725
BANKNIFTY10MAR2132300PE.NFO: 25
BANKNIFTY10MAR2132400PE.NFO: 675
BANKNIFTY10MAR2132500CE.NFO: 0
BANKNIFTY10MAR2132500PE.NFO: 609050
BANKNIFTY10MAR2132600PE.NFO: 1750
BANKNIFTY10MAR2132700PE.NFO: 2850
BANKNIFTY10MAR2132800PE.NFO: 1900
BANKNIFTY10MAR2132900PE.NFO: 4100
BANKNIFTY10MAR2133000CE.NFO: 500
BANKNIFTY10MAR2133000PE.NFO: 10127875
BANKNIFTY10MAR2133100PE.NFO: 6150
BANKNIFTY10MAR2133200PE.NFO: 13150
BANKNIFTY10MAR2133300PE.NFO: 59300
BANKNIFTY10MAR2133400PE.NFO: 25200
BANKNIFTY10MAR2133500CE.NFO: 76125
BANKNIFTY10MAR2133500PE.NFO: 6581175
BANKNIFTY10MAR2133600PE.NFO: 55200
BANKNIFTY10MAR2133700PE.NFO: 22875
BANKNIFTY10MAR2133800CE.NFO: 175
BANKNIFTY10MAR2133800PE.NFO: 58775
BANKNIFTY10MAR2133900PE.NFO: 39075
BANKNIFTY10MAR2134000CE.NFO: 324950
BANKNIFTY10MAR2134000PE.NFO: 12649700
BANKNIFTY10MAR2134100CE.NFO: 0
BANKNIFTY10MAR2134100PE.NFO: 161550
BANKNIFTY10MAR2134200PE.NFO: 457525
BANKNIFTY10MAR2134300CE.NFO: 50
BANKNIFTY10MAR2134300PE.NFO: 346550
BANKNIFTY10MAR2134400CE.NFO: 100
BANKNIFTY10MAR2134400PE.NFO: 277775
BANKNIFTY10MAR2134500CE.NFO: 532975
BANKNIFTY10MAR2134500PE.NFO: 11529300
BANKNIFTY10MAR2134600CE.NFO: 8275
BANKNIFTY10MAR2134600PE.NFO: 352650
BANKNIFTY10MAR2134700CE.NFO: 11700
BANKNIFTY10MAR2134700PE.NFO: 300025
BANKNIFTY10MAR2134800CE.NFO: 119900
BANKNIFTY10MAR2134800PE.NFO: 1139000
BANKNIFTY10MAR2134900CE.NFO: 37400
BANKNIFTY10MAR2134900PE.NFO: 431700
BANKNIFTY10MAR2135000CE.NFO: 8228725
BANKNIFTY10MAR2135000PE.NFO: 14825050
BANKNIFTY10MAR2135100CE.NFO: 380800
BANKNIFTY10MAR2135100PE.NFO: 454575
BANKNIFTY10MAR2135200CE.NFO: 686200
BANKNIFTY10MAR2135200PE.NFO: 553450
BANKNIFTY10MAR2135300CE.NFO: 895600
BANKNIFTY10MAR2135300PE.NFO: 804700
BANKNIFTY10MAR2135400CE.NFO: 528750
BANKNIFTY10MAR2135400PE.NFO: 360875
BANKNIFTY10MAR2135500CE.NFO: 11089000
BANKNIFTY10MAR2135500PE.NFO: 3858375
BANKNIFTY10MAR2135600CE.NFO: 1177550
BANKNIFTY10MAR2135600PE.NFO: 255675
BANKNIFTY10MAR2135700CE.NFO: 756300
BANKNIFTY10MAR2135700PE.NFO: 45400
BANKNIFTY10MAR2135800CE.NFO: 971775
BANKNIFTY10MAR2135800PE.NFO: 31300
BANKNIFTY10MAR2135900CE.NFO: 428575
BANKNIFTY10MAR2135900PE.NFO: 16025
BANKNIFTY10MAR2136000CE.NFO: 20877250
BANKNIFTY10MAR2136000PE.NFO: 2658925
BANKNIFTY10MAR2136100CE.NFO: 310900
BANKNIFTY10MAR2136100PE.NFO: 7150
BANKNIFTY10MAR2136200CE.NFO: 679750
BANKNIFTY10MAR2136200PE.NFO: 13350
BANKNIFTY10MAR2136300CE.NFO: 291275
BANKNIFTY10MAR2136300PE.NFO: 1800
BANKNIFTY10MAR2136400CE.NFO: 879050
BANKNIFTY10MAR2136400PE.NFO: 875
BANKNIFTY10MAR2136500CE.NFO: 21916275
BANKNIFTY10MAR2136500PE.NFO: 390450
BANKNIFTY10MAR2136600CE.NFO: 559525
BANKNIFTY10MAR2136600PE.NFO: 700
BANKNIFTY10MAR2136700CE.NFO: 316500
BANKNIFTY10MAR2136700PE.NFO: 50
BANKNIFTY10MAR2136800CE.NFO: 170125
BANKNIFTY10MAR2136800PE.NFO: 150
BANKNIFTY10MAR2136900CE.NFO: 100100
BANKNIFTY10MAR2137000CE.NFO: 29748550
BANKNIFTY10MAR2137000PE.NFO: 489400
BANKNIFTY10MAR2137100CE.NFO: 138150
BANKNIFTY10MAR2137200CE.NFO: 120275
BANKNIFTY10MAR2137300CE.NFO: 83450
BANKNIFTY10MAR2137400CE.NFO: 53725
BANKNIFTY10MAR2137500CE.NFO: 16954500
BANKNIFTY10MAR2137500PE.NFO: 6175
BANKNIFTY10MAR2137600CE.NFO: 36350
BANKNIFTY10MAR2137700CE.NFO: 12250
BANKNIFTY10MAR2137800CE.NFO: 279400
BANKNIFTY10MAR2137900CE.NFO: 4650
BANKNIFTY10MAR2138000CE.NFO: 17859600
BANKNIFTY10MAR2138000PE.NFO: 150
BANKNIFTY10MAR2138100CE.NFO: 7550
BANKNIFTY10MAR2138200CE.NFO: 4850
BANKNIFTY10MAR2138300CE.NFO: 7500
BANKNIFTY10MAR2138500CE.NFO: 5148475
BANKNIFTY10MAR2138600CE.NFO: 6375
BANKNIFTY10MAR2138900CE.NFO: 28000
BANKNIFTY10MAR2139000CE.NFO: 8754675
BANKNIFTY10MAR2139100CE.NFO: 20325
BANKNIFTY10MAR2139500CE.NFO: 1867450
BANKNIFTY10MAR2140000CE.NFO: 4695650
BANKNIFTY10MAR2140300CE.NFO: 150
BANKNIFTY18MAR2132000PE.NFO: 1075
BANKNIFTY18MAR2134000PE.NFO: 49400
BANKNIFTY18MAR2134500PE.NFO: 200
BANKNIFTY18MAR2135000CE.NFO: 1400
BANKNIFTY18MAR2135100PE.NFO: 25
BANKNIFTY18MAR2135500CE.NFO: 6075
BANKNIFTY18MAR2135500PE.NFO: 25
BANKNIFTY18MAR2135600CE.NFO: 0
BANKNIFTY18MAR2136000CE.NFO: 7675
BANKNIFTY18MAR2136200CE.NFO: 875
BANKNIFTY18MAR2136500CE.NFO: 4350
BANKNIFTY18MAR2136600CE.NFO: 200
BANKNIFTY18MAR2137500CE.NFO: 7300
BANKNIFTY18MAR2140000CE.NFO: 550
BANKNIFTY18MAR2140300CE.NFO: 125
BANKNIFTY22APR2133000CE.NFO: 1500
BANKNIFTY25MAR2121000PE.NFO: 16775
BANKNIFTY25MAR2122000PE.NFO: 102800
BANKNIFTY25MAR2123000PE.NFO: 50
BANKNIFTY25MAR2125000CE.NFO: 13050
BANKNIFTY25MAR2125000PE.NFO: 6279200
BANKNIFTY25MAR2126000PE.NFO: 308400
BANKNIFTY25MAR2127000CE.NFO: 34200
BANKNIFTY25MAR2127000PE.NFO: 922250
BANKNIFTY25MAR2127500CE.NFO: 2750
BANKNIFTY25MAR2127500PE.NFO: 94300
BANKNIFTY25MAR2128000CE.NFO: 14200
BANKNIFTY25MAR2128000PE.NFO: 2015025
BANKNIFTY25MAR2128500PE.NFO: 90600
BANKNIFTY25MAR2129000CE.NFO: 23075
BANKNIFTY25MAR2129000PE.NFO: 4396475
BANKNIFTY25MAR2129500CE.NFO: 10575
BANKNIFTY25MAR2129500PE.NFO: 498975
BANKNIFTY25MAR2130000CE.NFO: 219425
BANKNIFTY25MAR2130000PE.NFO: 40581900
BANKNIFTY25MAR2130500CE.NFO: 5750
BANKNIFTY25MAR2130500PE.NFO: 2701800
BANKNIFTY25MAR2130900PE.NFO: 50
BANKNIFTY25MAR2131000CE.NFO: 106775
BANKNIFTY25MAR2131000PE.NFO: 13698475
BANKNIFTY25MAR2131100PE.NFO: 12425
BANKNIFTY25MAR2131400PE.NFO: 350
BANKNIFTY25MAR2131500CE.NFO: 11975
BANKNIFTY25MAR2131500PE.NFO: 3893450
BANKNIFTY25MAR2131600PE.NFO: 9925
BANKNIFTY25MAR2131800CE.NFO: 150
BANKNIFTY25MAR2131800PE.NFO: 24300
BANKNIFTY25MAR2131900PE.NFO: 350
BANKNIFTY25MAR2132000CE.NFO: 645950
BANKNIFTY25MAR2132000PE.NFO: 29618625
BANKNIFTY25MAR2132100PE.NFO: 308700
BANKNIFTY25MAR2132200PE.NFO: 230250
BANKNIFTY25MAR2132300CE.NFO: 25
BANKNIFTY25MAR2132300PE.NFO: 17800
BANKNIFTY25MAR2132400CE.NFO: 450
BANKNIFTY25MAR2132400PE.NFO: 637675
BANKNIFTY25MAR2132500CE.NFO: 33700
BANKNIFTY25MAR2132500PE.NFO: 23811525
BANKNIFTY25MAR2132600PE.NFO: 1028025
BANKNIFTY25MAR2132700PE.NFO: 432075
BANKNIFTY25MAR2132800CE.NFO: 50
BANKNIFTY25MAR2132800PE.NFO: 22850
BANKNIFTY25MAR2132900PE.NFO: 472825
BANKNIFTY25MAR2133000CE.NFO: 5138225
BANKNIFTY25MAR2133000PE.NFO: 63510725
BANKNIFTY25MAR2133100PE.NFO: 494100
BANKNIFTY25MAR2133200CE.NFO: 1075
BANKNIFTY25MAR2133200PE.NFO: 506125
BANKNIFTY25MAR2133300PE.NFO: 187250
BANKNIFTY25MAR2133400CE.NFO: 50
BANKNIFTY25MAR2133400PE.NFO: 74300
BANKNIFTY25MAR2133500CE.NFO: 267100
BANKNIFTY25MAR2133500PE.NFO: 33998900
BANKNIFTY25MAR2133600CE.NFO: 475
BANKNIFTY25MAR2133600PE.NFO: 281425
BANKNIFTY25MAR2133700CE.NFO: 50
BANKNIFTY25MAR2133700PE.NFO: 125950
BANKNIFTY25MAR2133800CE.NFO: 25
BANKNIFTY25MAR2133800PE.NFO: 2980325
BANKNIFTY25MAR2133900PE.NFO: 1457575
BANKNIFTY25MAR2134000CE.NFO: 49074825
BANKNIFTY25MAR2134000PE.NFO: 116032850
BANKNIFTY25MAR2134100CE.NFO: 1025
BANKNIFTY25MAR2134100PE.NFO: 1268450
BANKNIFTY25MAR2134200CE.NFO: 575
BANKNIFTY25MAR2134200PE.NFO: 2449650
BANKNIFTY25MAR2134300CE.NFO: 1700
BANKNIFTY25MAR2134300PE.NFO: 748500
BANKNIFTY25MAR2134400CE.NFO: 2775
BANKNIFTY25MAR2134400PE.NFO: 597650
BANKNIFTY25MAR2134500CE.NFO: 2698650
BANKNIFTY25MAR2134500PE.NFO: 47756750
BANKNIFTY25MAR2134600CE.NFO: 11900
BANKNIFTY25MAR2134600PE.NFO: 1181050
BANKNIFTY25MAR2134700CE.NFO: 42825
BANKNIFTY25MAR2134700PE.NFO: 4080400
BANKNIFTY25MAR2134800CE.NFO: 532425
BANKNIFTY25MAR2134800PE.NFO: 2388200
BANKNIFTY25MAR2134900CE.NFO: 253975
BANKNIFTY25MAR2134900PE.NFO: 582900
BANKNIFTY25MAR2135000CE.NFO: 55624025
BANKNIFTY25MAR2135000PE.NFO: 82004150
BANKNIFTY25MAR2135100CE.NFO: 806025
BANKNIFTY25MAR2135100PE.NFO: 1382250
BANKNIFTY25MAR2135200CE.NFO: 1655075
BANKNIFTY25MAR2135200PE.NFO: 1889550
BANKNIFTY25MAR2135300CE.NFO: 4133850
BANKNIFTY25MAR2135300PE.NFO: 8026175
BANKNIFTY25MAR2135400CE.NFO: 1733300
BANKNIFTY25MAR2135400PE.NFO: 1626750
BANKNIFTY25MAR2135500CE.NFO: 48788225
BANKNIFTY25MAR2135500PE.NFO: 37361775
BANKNIFTY25MAR2135600CE.NFO: 2595650
BANKNIFTY25MAR2135600PE.NFO: 576875
BANKNIFTY25MAR2135700CE.NFO: 1479825
BANKNIFTY25MAR2135700PE.NFO: 208725
BANKNIFTY25MAR2135800CE.NFO: 1506275
BANKNIFTY25MAR2135800PE.NFO: 188725
BANKNIFTY25MAR2135900CE.NFO: 1242475
BANKNIFTY25MAR2135900PE.NFO: 104675
BANKNIFTY25MAR2136000CE.NFO: 81176150
BANKNIFTY25MAR2136000PE.NFO: 29004625
BANKNIFTY25MAR2136100CE.NFO: 735875
BANKNIFTY25MAR2136100PE.NFO: 146375
BANKNIFTY25MAR2136200CE.NFO: 2630975
BANKNIFTY25MAR2136200PE.NFO: 15725
BANKNIFTY25MAR2136300CE.NFO: 1029425
BANKNIFTY25MAR2136300PE.NFO: 41200
BANKNIFTY25MAR2136400CE.NFO: 969075
BANKNIFTY25MAR2136400PE.NFO: 33625
BANKNIFTY25MAR2136500CE.NFO: 65001875
BANKNIFTY25MAR2136500PE.NFO: 11259875
BANKNIFTY25MAR2136600CE.NFO: 1736000
BANKNIFTY25MAR2136600PE.NFO: 14500
BANKNIFTY25MAR2136700CE.NFO: 1073675
BANKNIFTY25MAR2136700PE.NFO: 17675
BANKNIFTY25MAR2136800CE.NFO: 6033700
BANKNIFTY25MAR2136800PE.NFO: 18050
BANKNIFTY25MAR2136900CE.NFO: 403225
BANKNIFTY25MAR2136900PE.NFO: 6075
BANKNIFTY25MAR2137000CE.NFO: 100783200
BANKNIFTY25MAR2137000PE.NFO: 13573175
BANKNIFTY25MAR2137100CE.NFO: 880000
BANKNIFTY25MAR2137100PE.NFO: 2750
BANKNIFTY25MAR2137200CE.NFO: 1301950
BANKNIFTY25MAR2137200PE.NFO: 3675
BANKNIFTY25MAR2137300CE.NFO: 736750
BANKNIFTY25MAR2137300PE.NFO: 2225
BANKNIFTY25MAR2137400CE.NFO: 2369825
BANKNIFTY25MAR2137400PE.NFO: 750
BANKNIFTY25MAR2137500CE.NFO: 59748050
BANKNIFTY25MAR2137500PE.NFO: 448350
BANKNIFTY25MAR2137600CE.NFO: 1678425
BANKNIFTY25MAR2137600PE.NFO: 225
BANKNIFTY25MAR2137700CE.NFO: 146100
BANKNIFTY25MAR2137700PE.NFO: 125
BANKNIFTY25MAR2137800CE.NFO: 147000
BANKNIFTY25MAR2137900CE.NFO: 39800
BANKNIFTY25MAR2138000CE.NFO: 80485725
BANKNIFTY25MAR2138000PE.NFO: 1009800
BANKNIFTY25MAR2138100CE.NFO: 196250
BANKNIFTY25MAR2138100PE.NFO: 50
BANKNIFTY25MAR2138200CE.NFO: 319300
BANKNIFTY25MAR2138300CE.NFO: 16175
BANKNIFTY25MAR2138300PE.NFO: 25
BANKNIFTY25MAR2138400CE.NFO: 13875
BANKNIFTY25MAR2138400PE.NFO: 25
BANKNIFTY25MAR2138500CE.NFO: 39825850
BANKNIFTY25MAR2138500PE.NFO: 5475
BANKNIFTY25MAR2138600CE.NFO: 875
BANKNIFTY25MAR2138700CE.NFO: 14450
BANKNIFTY25MAR2138800CE.NFO: 1292050
BANKNIFTY25MAR2138900CE.NFO: 1650
BANKNIFTY25MAR2139000CE.NFO: 57631250
BANKNIFTY25MAR2139000PE.NFO: 729575
BANKNIFTY25MAR2139100CE.NFO: 227300
BANKNIFTY25MAR2139200CE.NFO: 100
BANKNIFTY25MAR2139400CE.NFO: 2225
BANKNIFTY25MAR2139500CE.NFO: 4693200
BANKNIFTY25MAR2139500PE.NFO: 575
BANKNIFTY25MAR2140000CE.NFO: 51966525
BANKNIFTY25MAR2140000PE.NFO: 704125
BANKNIFTY25MAR2140300CE.NFO: 290350
BANKNIFTY25MAR2140300PE.NFO: 0
BANKNIFTY27MAY2133500PE.NFO: 50
BANKNIFTY29APR2129000PE.NFO: 99525
BANKNIFTY29APR2130000PE.NFO: 32900
BANKNIFTY29APR2131000PE.NFO: 39325
BANKNIFTY29APR2131500PE.NFO: 50
BANKNIFTY29APR2132000CE.NFO: 2525
BANKNIFTY29APR2132000PE.NFO: 255450
BANKNIFTY29APR2133000PE.NFO: 302675
BANKNIFTY29APR2133100PE.NFO: 75
BANKNIFTY29APR2133500PE.NFO: 950
BANKNIFTY29APR2134000CE.NFO: 7825
BANKNIFTY29APR2134000PE.NFO: 230100
BANKNIFTY29APR2134200PE.NFO: 0
BANKNIFTY29APR2134300CE.NFO: 25
BANKNIFTY29APR2134500PE.NFO: 13325
BANKNIFTY29APR2134700CE.NFO: 25
BANKNIFTY29APR2134800PE.NFO: 0
BANKNIFTY29APR2134900CE.NFO: 25
BANKNIFTY29APR2134900PE.NFO: 50
BANKNIFTY29APR2135000CE.NFO: 261950
BANKNIFTY29APR2135000PE.NFO: 373100
BANKNIFTY29APR2135100PE.NFO: 25
BANKNIFTY29APR2135200CE.NFO: 25
BANKNIFTY29APR2135200PE.NFO: 75
BANKNIFTY29APR2135300CE.NFO: 75
BANKNIFTY29APR2135300PE.NFO: 0
BANKNIFTY29APR2135400CE.NFO: 25
BANKNIFTY29APR2135400PE.NFO: 25
BANKNIFTY29APR2135500CE.NFO: 12000
BANKNIFTY29APR2135500PE.NFO: 5650
BANKNIFTY29APR2135600PE.NFO: 25
BANKNIFTY29APR2135700CE.NFO: 25
BANKNIFTY29APR2135700PE.NFO: 25
BANKNIFTY29APR2135800CE.NFO: 0
BANKNIFTY29APR2135800PE.NFO: 150
BANKNIFTY29APR2135900CE.NFO: 25
BANKNIFTY29APR2136000CE.NFO: 594400
BANKNIFTY29APR2136000PE.NFO: 163725
BANKNIFTY29APR2136100PE.NFO: 25
BANKNIFTY29APR2136200CE.NFO: 0
BANKNIFTY29APR2136200PE.NFO: 0
BANKNIFTY29APR2136400CE.NFO: 0
BANKNIFTY29APR2136500CE.NFO: 12575
BANKNIFTY29APR2136500PE.NFO: 1450
BANKNIFTY29APR2136700PE.NFO: 0
BANKNIFTY29APR2136900PE.NFO: 25
BANKNIFTY29APR2137000CE.NFO: 370825
BANKNIFTY29APR2137000PE.NFO: 43275
BANKNIFTY29APR2137100PE.NFO: 0
BANKNIFTY29APR2137500CE.NFO: 54675
BANKNIFTY29APR2138000CE.NFO: 734025
BANKNIFTY29APR2138000PE.NFO: 1050
BANKNIFTY29APR2138500CE.NFO: 9975
BANKNIFTY29APR2139000CE.NFO: 64025
BANKNIFTY29APR2139500CE.NFO: 375
BANKNIFTY29APR2140000CE.NFO: 800525
BANKNIFTY-I.NFO: 570507075
BANKNIFTY-II.NFO: 113260375
BANKNIFTY-III.NFO: 48329025
====================
11MAR21
--------------------
====================
18MAR21
--------------------
====================
25MAR21
--------------------
====================

### 2) The current data is for 1 minute interval. Make it in a way that it is available at 3 minutes, 5 minutes, 15 minutes & 60 minutes interval.

In [112]:
df.head()

,Ticker,Date,Time,Open,High,Low,Close,Volume,Open Interest
0,BANKNIFTY01APR2130600CE.NFO,2021-03-01 14:39:59,14:39:59,5057.2,5065.0,5057.20,5065.00,50,48000
1,BANKNIFTY01APR2130600CE.NFO,2021-03-01 15:09:59,15:09:59,5065.0,5065.0,4604.95,4604.95,25,48000
2,BANKNIFTY01APR2130700CE.NFO,2021-03-01 15:00:59,15:00:59,4855.0,4860.0,4855.00,4860.00,100,48000
3,BANKNIFTY01APR2130700PE.NFO,2021-03-01 14:14:59,14:14:59,140.6,140.6,137.00,137.00,4550,47750
4,BANKNIFTY01APR2130700PE.NFO,2021-03-01 14:15:59,14:15:59,137.0,143.6,137.00,140.00,4550,47750

In [113]:
# df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)

In [114]:
# Define a list of resampling intervals
resample_intervals = ['3T', '5T', '15T', '60T']

In [115]:
# Resample the data for each interval and calculate OHLCV and open interest data
resampled_data = {}
for interval in resample_intervals:
    resampled_df = df.resample(interval).agg({
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
        'Volume': 'sum',
        'Open Interest': 'last'
    })
    resampled_data[interval] = resampled_df.dropna()

In [116]:
df.head()

,Ticker,Time,Open,High,Low,Close,Volume,Open Interest
Date,,,,,,,,
2021-03-01 14:39:59,BANKNIFTY01APR2130600CE.NFO,14:39:59,5057.2,5065.0,5057.20,5065.00,50,48000
2021-03-01 15:09:59,BANKNIFTY01APR2130600CE.NFO,15:09:59,5065.0,5065.0,4604.95,4604.95,25,48000
2021-03-01 15:00:59,BANKNIFTY01APR2130700CE.NFO,15:00:59,4855.0,4860.0,4855.00,4860.00,100,48000
2021-03-01 14:14:59,BANKNIFTY01APR2130700PE.NFO,14:14:59,140.6,140.6,137.00,137.00,4550,47750
2021-03-01 14:15:59,BANKNIFTY01APR2130700PE.NFO,14:15:59,137.0,143.6,137.00,140.00,4550,47750

In [117]:
df.head()

,Ticker,Time,Open,High,Low,Close,Volume,Open Interest
Date,,,,,,,,
2021-03-01 14:39:59,BANKNIFTY01APR2130600CE.NFO,14:39:59,5057.2,5065.0,5057.20,5065.00,50,48000
2021-03-01 15:09:59,BANKNIFTY01APR2130600CE.NFO,15:09:59,5065.0,5065.0,4604.95,4604.95,25,48000
2021-03-01 15:00:59,BANKNIFTY01APR2130700CE.NFO,15:00:59,4855.0,4860.0,4855.00,4860.00,100,48000
2021-03-01 14:14:59,BANKNIFTY01APR2130700PE.NFO,14:14:59,140.6,140.6,137.00,137.00,4550,47750
2021-03-01 14:15:59,BANKNIFTY01APR2130700PE.NFO,14:15:59,137.0,143.6,137.00,140.00,4550,47750

In [118]:
# Print the resampled data for each interval
for interval, data in resampled_data.items():
    print(interval)
    print("-" * 77)
    print(data)
    print("=" * 30)

3T
-----------------------------------------------------------------------------
                      Open      High    Low     Close   Volume  Open Interest
Date
2021-03-01 09:15:00   6.25  35492.35   3.00  35470.00  7666300         218800
2021-03-01 09:18:00   6.00  35500.00   3.05  35463.55  4754125         218825
2021-03-01 09:21:00   6.25  35507.95   5.25  35410.00  5768050         219000
2021-03-01 09:24:00   5.80  35500.00   5.05  35471.30  3686750         219000
2021-03-01 09:27:00   5.40  35480.80   5.20  35382.65  5810400         218925
...                    ...       ...    ...       ...      ...            ...
2021-03-01 15:18:00   3.95  35555.00   3.90  35500.00  3923075         292500
2021-03-01 15:21:00   4.15  35514.05   3.30  35514.05  4034550         292525
2021-03-01 15:24:00   3.40  35546.55   3.40  35469.30  3740375         359825
2021-03-01 15:27:00   3.40  35546.55   3.35  35545.00  2818725         292450
2021-03-01 15:30:00  11.95   1170.60  11.00    419.60     5200          11300

[126 rows x 6 columns]
==============================
5T
-----------------------------------------------------------------------------
                      Open      High    Low     Close    Volume  Open Interest
Date
2021-03-01 09:15:00   6.25  35492.35   3.00  35366.90  10287200         282325
2021-03-01 09:20:00   5.90  35507.95   3.05  35485.00   9027650         219000
2021-03-01 09:25:00   5.65  35500.00   5.05  35382.65   8370775         218925
2021-03-01 09:30:00   5.65  35382.65   5.35  35186.20  12664775         281725
2021-03-01 09:35:00   6.25  35430.00   5.45  35430.00   7251150         219025
...                    ...       ...    ...       ...       ...            ...
2021-03-01 15:10:00   4.35  35500.00   4.35  35500.00   5442325         287525
2021-03-01 15:15:00   4.85  35555.00   3.70  35555.00   5726150         292500
2021-03-01 15:20:00   4.15  35555.00   3.30  35514.05   7162025         292525
2021-03-01 15:25:00   3.40  35546.55   3.35  35545.00   5198725         292450
2021-03-01 15:30:00  11.95   1170.60  11.00    419.60      5200          11300

[76 rows x 6 columns]
==============================
15T
-----------------------------------------------------------------------------
                        Open      High    Low     Close    Volume  \
Date
2021-03-01 09:15:00     6.25  35507.95   3.00  35382.65  27685625
2021-03-01 09:30:00     5.65  35530.50   5.35  35530.50  25778225
2021-03-01 09:45:00     5.35  35610.00   5.10  35530.00  18303200
2021-03-01 10:00:00     5.40  35530.00   5.00  35453.70  11916875
2021-03-01 10:15:00     5.05  35700.00   4.75  35700.00  13730550
2021-03-01 10:30:00     4.80  35750.00   3.05  35650.00  13182075
2021-03-01 10:45:00     4.45  35706.40   4.45  35628.10  10114850
2021-03-01 11:00:00     4.75  35660.00   4.50  35485.00   8362625
2021-03-01 11:15:00     4.50  35656.25   4.45  35500.00  11241525
2021-03-01 11:30:00     5.30  35607.50   4.75  35421.95  15112450
2021-03-01 11:45:00     5.15  35421.95   3.85  35410.00  16459525
2021-03-01 12:00:00     5.40  35410.00   4.75  35410.00  12500650
2021-03-01 12:15:00     4.90  35410.00   4.60  35183.25  14982050
2021-03-01 12:30:00     5.85  35296.00   5.50  35280.30  13764250
2021-03-01 12:45:00     6.00  35432.50   5.50  35280.50  12642750
2021-03-01 13:00:00     5.85  35508.80   3.85  35508.80  13109025
2021-03-01 13:15:00     5.45  35530.80   5.10  35480.00  11409550
2021-03-01 13:30:00     5.20  35623.45   4.75  35538.05  15709625
2021-03-01 13:45:00     5.20  35615.10   5.05  35421.85  11421975
2021-03-01 14:00:00     5.50  35575.70   5.40  35486.45  10740875
2021-03-01 14:15:00   137.00  35588.00   5.50  35450.00  14092000
2021-03-01 14:30:00     6.20  35580.05   4.70  35465.70  13643350
2021-03-01 14:45:00     4.85  35575.10   4.25  35392.80  15884025
2021-03-01 15:00:00  4855.00  35500.00   4.05  35500.00  15139875
2021-03-01 15:15:00     4.85  35555.00   3.30  35545.00  18086900
2021-03-01 15:30:00    11.95   1170.60  11.00    419.60      5200

                     Open Interest
Date
2021-03-01 09:15:00         218925
2021-03-01 09:30:00         219025
2021-03-01 09:45:00         219200
2021-03-01 10:00:00         282375
2021-03-01 10:15:00         219350
2021-03-01 10:30:00         282650
2021-03-01 10:45:00         282825
2021-03-01 11:00:00        1498575
2021-03-01 11:15:00         282975
2021-03-01 11:30:00         220300
2021-03-01 11:45:00         223825
2021-03-01 12:00:00         259825
2021-03-01 12:15:00         260250
2021-03-01 12:30:00         282750
2021-03-01 12:45:00         346825
2021-03-01 13:00:00         279125
2021-03-01 13:15:00         347950
2021-03-01 13:30:00         357600
2021-03-01 13:45:00         357450
2021-03-01 14:00:00         357600
2021-03-01 14:15:00         287450
2021-03-01 14:30:00         357825
2021-03-01 14:45:00         287475
2021-03-01 15:00:00         287525
2021-03-01 15:15:00         292450
2021-03-01 15:30:00          11300
==============================
60T
-----------------------------------------------------------------------------
                        Open      High   Low     Close    Volume  \
Date
2021-03-01 09:00:00     6.25  35610.00  3.00  35530.00  71767050
2021-03-01 10:00:00     5.40  35750.00  3.05  35628.10  48944350
2021-03-01 11:00:00     4.75  35660.00  3.85  35410.00  51176125
2021-03-01 12:00:00     5.40  35432.50  4.60  35280.50  53889700
2021-03-01 13:00:00     5.85  35623.45  3.85  35421.85  51650175
2021-03-01 14:00:00     5.50  35588.00  4.25  35392.80  54360250
2021-03-01 15:00:00  4855.00  35555.00  3.30    419.60  33231975

                     Open Interest
Date
2021-03-01 09:00:00         219200
2021-03-01 10:00:00         282825
2021-03-01 11:00:00         223825
2021-03-01 12:00:00         346825
2021-03-01 13:00:00         357450
2021-03-01 14:00:00         287475
2021-03-01 15:00:00          11300
==============================

# Bonus Task

### 3) Calculate the Implied Volatility for all the options (you need to research on how to calculate implied volatility in python) . Based on the Future price (BANKNIFTY-I NFO Close price) (Can use libraries for the same)

In [119]:
import py_vollib.black_scholes.implied_volatility as iv

In [120]:
# Filtering the data to only include options data
# options_data = df[df['Ticker'].str.contains('BANKNIFTY')]

In [121]:
# Calculate the Future price based on the last Close price of BANKNIFTY
future_price = df[df['Ticker'] == 'BANKNIFTY01APR2130600CE.NFO']['Close'].iloc[-1]

In [122]:
# Function to calculate the implied volatility
def get_implied_volatility(row):
    try:
        # Calculate the option price using Black Scholes model
        option_price = iv.implied_volatility_of_undiscounted_option_price(row['Close'], future_price, row['Strike'], row['Days_to_expiry']/365, row['Interest_Rate']/100, row['Option_Type'].lower())

        return option_price
    except:
        return np.nan

In [123]:
# Apply the function to each row in the dataset
df['Implied_Volatility'] = df.apply(get_implied_volatility, axis=1)

# Print the dataset with the implied volatility
print(df)

                                          Ticker      Time      Open  \
Date
2021-03-01 14:39:59  BANKNIFTY01APR2130600CE.NFO  14:39:59   5057.20
2021-03-01 15:09:59  BANKNIFTY01APR2130600CE.NFO  15:09:59   5065.00
2021-03-01 15:00:59  BANKNIFTY01APR2130700CE.NFO  15:00:59   4855.00
2021-03-01 14:14:59  BANKNIFTY01APR2130700PE.NFO  14:14:59    140.60
2021-03-01 14:15:59  BANKNIFTY01APR2130700PE.NFO  14:15:59    137.00
...                                          ...       ...       ...
2021-03-01 15:20:59            BANKNIFTY-III.NFO  15:20:59  35555.00
2021-03-01 15:23:59            BANKNIFTY-III.NFO  15:23:59  35500.00
2021-03-01 15:24:59            BANKNIFTY-III.NFO  15:24:59  35514.05
2021-03-01 15:25:59            BANKNIFTY-III.NFO  15:25:59  35514.05
2021-03-01 15:29:59            BANKNIFTY-III.NFO  15:29:59  35546.55

                         High       Low     Close  Volume  Open Interest  \
Date
2021-03-01 14:39:59   5065.00   5057.20   5065.00      50          48000
2021-03-01 15:09:59   5065.00   4604.95   4604.95      25          48000
2021-03-01 15:00:59   4860.00   4855.00   4860.00     100          48000
2021-03-01 14:14:59    140.60    137.00    137.00    4550          47750
2021-03-01 14:15:59    143.60    137.00    140.00    4550          47750
...                       ...       ...       ...     ...            ...
2021-03-01 15:20:59  35555.00  35500.00  35500.00     100         292500
2021-03-01 15:23:59  35514.05  35500.00  35514.05      25         292525
2021-03-01 15:24:59  35514.05  35514.05  35514.05      50         292525
2021-03-01 15:25:59  35546.55  35514.05  35546.55      25         292475
2021-03-01 15:29:59  35546.55  35543.00  35545.00      75         292450

                     Implied_Volatility
Date
2021-03-01 14:39:59                 NaN
2021-03-01 15:09:59                 NaN
2021-03-01 15:00:59                 NaN
2021-03-01 14:14:59                 NaN
2021-03-01 14:15:59                 NaN
...                                 ...
2021-03-01 15:20:59                 NaN
2021-03-01 15:23:59                 NaN
2021-03-01 15:24:59                 NaN
2021-03-01 15:25:59                 NaN
2021-03-01 15:29:59                 NaN

[82865 rows x 9 columns]

Getting many NaN values while calculating implied volatility which shows that for those rows data is insufficient to calculate implied volatility. Some parameters are missing such as strike price.

#### Submitted by:- Jaismeen